#pragma config(Sensor, dgtl1,  Distance,       sensorQuadEncoder)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////
//-|-------------------------------------|-//
//-| Sample Code On Comparative Function |-//
//-|-------------------------------------|-//
/////////////////////////////////////////////

//Include Competition Language
#include "Competition Language.c"

task main(){
	int goal;

	//Configure Drive
	setDrive(leftDrive, rightDrive);
	configDrive;

	while(1 == 1){

		//Set "goal" To Joystick Channel
		goal = vexRT[Ch3];

		//Take The Larger Of "goal" and -63, (Set Minimum)
		goal = max(goal, -63);

		//Take The Smaller Of "goal" and 63, (Set Maximum)
		goal = min(goal, 63);

		if(SensorValue[Distance] > goal){
			singleJoystick(-127, 0);
		}
		else{
			singleJoystick(127, 0);
		}
	}
}
