#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           mtr,           tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////
//-|----------------------------|-//
//-| Sample Code On Conversions |-//
//-|----------------------------|-//
////////////////////////////////////

//Include Competition Language
#include "Competition Language.c"

task main(){
	int value = 4ft + 8in;									//4 Feet 8 Inches
	value = 6rot + 5deg;										//6 Full Rotations And 5 More Degrees
	value = 6minutes + 24sec + 500millisec;	//6 Minutes 24 Seconds And Half A Second
}
